# Generated by Django 4.2.28 on 2026-02-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_booking_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MenuItem",
            new_name="Menu",
        ),
    ]


